### ISSUE TITLE
Apps are not signed

### ISSUE THREAD

**Issue by gingerbeardman** [kfix/MacPin#19]
![screen shot 2016-03-29 at 10 51 37](https://cloud.githubusercontent.com/assets/49612/14104283/464e1f6e-f59c-11e5-8022-3a549c25aa4b.png)

**Comment by kfix** [comment]
I don’t have a Dev membership to sign with.
 You can hold Control and use the context menu to Open & override Gatekeeper.

**Comment by gingerbeardman** [comment]
Yes, that's my chosen workaround.
