### ISSUE TITLE
app signing is broken

### ISSUE THREAD

**Issue by jdhealy** [kfix/MacPin#2]
Downloaded the `MacPin.zip` for `1.3.0` from the Releases page.

Unzipped and right-clicked menu-opened Vine.app. App launched, but no windows opened.

From Console.app:

```
4/23/15 5:21:43.924 PM taskgated[100]: no application identifier provided, can't use provisioning profiles [pid=41137]
4/23/15 5:21:49.000 PM kernel[0]: Sandbox: Vine(41137) System Policy: deny file-write-unlink /Users/XXXXX/Library/Saved Application State/com.github.kfix.MacPin.Vine.savedState/restorecount.plist
```

Just FYI.

The app looks really cool. I'm going to try the makefile and play around with it. :smile:

**Comment by kfix** [comment]
Thanks for the report. I have another monster refactor push coming down the pipe today (classes broken up to start iOS subclasses). It should address this and some other bugs, I think the 1.3.0 binaries are broken.

**Comment by Psidium** [comment]
Still having this on 1.3.0  :/
for > 1.2.1 are completely broken

EDIT:
by enabling ad-hoc signing on the makefile I could run the app, but it wasn't retina
`defaults write com.github.kfix.MacPin.(site) AppleMagnifiedMode -bool no`
fixed it

**Comment by kfix** [comment]
okay, 1.3.0a2 is uploaded and uses ad-hoc signatures. it also bundles the Swift libs, which is why its huge.
I don't have another Mac to make a clean-room test of the package so another suck^H^H^H^H^Htester will have to try it for me.
thanks for your patience.

**Comment by Psidium** [comment]
Working on my mac out of the box, but no mac notifications.

**Comment by kfix** [comment]
W00t.
Are you trying the Hangouts app? that's the only one where I have native notifications pulled out via JS userscripts.
If you run it from the Terminal (~/Applications/Hangouts.app/Contents/MacOS/Hangouts), you should see  some log warnings indicating the notification attempts.

I have had issues in the past with bundle-id's getting blacklisted from making notifications because Finder thinks an app is corrupt or deleted. purging the app and restarting cured that for me, a long time ago.

**Comment by Psidium** [comment]
Nope, the log don't even tickle when I receive a message on Hangouts.

2015-05-27 4:17 GMT-03:00 Joey Korkames notifications@github.com:

> W00t.
> Are you trying the Hangouts app? that's the only one where I have native
> notifications pulled out via JS userscripts.
> If you run it from the Terminal
> (~/Applications/Hangouts.app/Contents/MacOS/Hangouts), you should see some
> log warnings indicating the notification attempts.
> 
> I have had issues in the past with bundle-id's getting blacklisted from
> making notifications because Finder thinks an app is corrupt or deleted.
> purging the app and restarting cured that for me, a long time ago.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kfix/MacPin/issues/2#issuecomment-105791145.

## 

Gabriel Borges Fernandes

**Comment by kfix** [comment]
@Psidium, try the 1.3.0a3 pre-release. Google changed the markup recently which broke MacPin's notification scraper.
