### ISSUE TITLE
Black border around address bar

### ISSUE THREAD

**Issue by gingerbeardman** [kfix/MacPin#20]
![screen shot 2016-03-29 at 10 54 22](https://cloud.githubusercontent.com/assets/49612/14104349/af5dfa6a-f59c-11e5-97a7-07b9778e3740.png)

Mac OS 10.11.4 (15E65)
MacPin 1.4.0

**Comment by kfix** [comment]
> On Mar 29, 2016, at 2:55 AM, Matt Sephton notifications@github.com wrote:
> 
>  https://cloud.githubusercontent.com/assets/49612/14104349/af5dfa6a-f59c-11e5-97a7-07b9778e3740.png
> Mac OS 10.11.4 (15E65)
> MacPin 1.4.0
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub https://github.com/kfix/MacPin/issues/20.

all my Macs are on Emo mode (so dark…) & I didn’t notice!

I’ll see if I can trace it down. This shortcut http://osxdaily.com/2014/10/24/enable-dark-mode-keyboard-shortcut-mac-os-x/ should be helpful.
