### ISSUE TITLE
Maverick support?

### ISSUE THREAD

**Issue by newoldschool** [kfix/MacPin#26]
Hello, I'm using osx 10.9.5, I downloaded your latest release but it seems is not compatible with maverick.
I just need hangouts and whatsapp, where can I find a download link for previous versions of this two apps?

I'm using macpin latest release in another mac with El Capitan and I'm very happy with everything, I would love to use this in Maverick too.

Can someone help me please?

Thanks!

ps: I'm not a programmer, I don't know anything about code, I found a few months ago MacPin and I was using the included apps. I need these apps for maverick please.

**Comment by newoldschool** [comment]
New info:
I copied the Hangouts app from my mac with El Capitan, and then moved that app to my other mac with Mavericks, but I can't use it neither.
But now I have an error message that says: "You cannot open the application...the Classic Environment is no longer supported`

It's so strange. I am able to use a Classis app in El capitan but not in Mavericks?

Any help is appreciated. Thank you.

**Comment by kfix** [comment]
Sorry, I didn't tag releases very well so you would have to checkout from an arbitrary commit (before El Capitan GM date) and build . But there's so many bug fixes in MacPin and OSX that it's simply not worth the effort. Why can't you upgrade?

**Comment by kfix** [comment]
I mean, why not upgrade to Yosemite? That's what's on my EOL 2009 MacMini which can build and run the swift2.3 branch for MacPin

**Comment by kfix** [comment]
see #27 for build instructions, the posted release is obsolete.
