### ISSUE TITLE
Retina support

### ISSUE THREAD

**Issue by anjiro** [kfix/MacPin#3]
MacPin doesn't seem to support retina displays. At least, the apps in release v1.3.0b1 are all fuzzy on my retina macbook pro.

**Comment by kfix** [comment]
I don't have a retina screen to test on. for b1, I tried setting some keys in the [Info.plist](https://github.com/kfix/MacPin/blob/master/templates/OSX/Info.plist#L375) to enable Cocoa's automatic scaling, since there's few NSImages in use.

**Comment by alfonsomga** [comment]
+1

Looks horrible..

**Comment by kfix** [comment]
Alfonsomga, +1's are not useful on GitHub or anywhere really. what version did you try?

**Comment by exwyezed** [comment]
Hey kfix, I tried v1.3.0b1.

**Comment by kfix** [comment]
Ok, I'll try simulating retina on my mini (http://stackoverflow.com/a/13596261) to debug it

**Comment by anjiro** [comment]
Works great, thanks for fixing it!

**Comment by exwyezed** [comment]
Same here, thank you kfix!
