### ISSUE TITLE
Example of multi-tab app?

### ISSUE THREAD

**Issue by codefriar** [kfix/MacPin#32]
Is it possible to create an 'app', that launches with two or more tabs? ie: facebook and messenger? I looked through the examples but couldn't find an example of that.

**Comment by kfix** [comment]
the sample sites/MacPin/main.js launches 3 tabs:
* docTab
* gitTab
* replTab

**Comment by codefriar** [comment]
@kfix - Thanks for that pointer. I had started there, but had an error which made me think it wasn't working. Happy to say it was a user error.
