### ISSUE TITLE
Will not compile on Big Sur

### ISSUE THREAD

**Issue by macOS26** [kfix/MacPin#37]
If you could update for big sur that'd be great!  Also an option for Xcode build projects were also be good.

**Comment by kfix** [comment]
Sorry, it's been on NO-maintenance mode for a bit.
Not sure when I'll be updating to the latest as I've kept my own workstation back on Catalina until I've got some off time to mess it up :-)

**Comment by kfix** [comment]
main branch compiles now on BS - YMMV as far as bugginess goes.

I _might_ add an xcodeproj for MacPin.app but the issue is that it doesn't really handle "app generation" for all the sites/*, but I suppose custom build scripts could be hooked in (using the uuuugly makefiles, at first)
