### ISSUE TITLE
Request - Glowing Bear

### ISSUE THREAD

**Issue by fuzzy76** [kfix/MacPin#5]
See https://glowing-bear.github.io/glowing-bear/

**Comment by kfix** [comment]
That's pretty cool! I was considering IRCCloud, but you pretty much need to $ubscribe to get scrollback.
I suppose I can just run WeeChat on a NAS or VM for ∞-lines.

I'm polishing up a HTML5 Notification JS-shim for Messenger.app and Trello.app, and I think GB can use it too. I'll package a new pre-release with this, maybe with a bundled checkout of GB for a little more resiliency.
