### ISSUE TITLE
No Trello board background colors

### ISSUE THREAD

**Issue by anjiro** [kfix/MacPin#6]
v 1.3.0; no matter the background color of the Trello board, the background is dark. (Left Firefox, right MacPin).
![trello_colors](https://cloud.githubusercontent.com/assets/386877/8438257/a939812c-1f32-11e5-8bec-7b9df007686d.png)

**Comment by kfix** [comment]
yeah, this is my styler.js at work. I'm too cheap to get Trello Gold....and the stock blue color messes with my sleep after night hacking.
I'll see if I can make it locally detect a Trello Gold user so as to not override the current background

**Comment by anjiro** [comment]
This isn't Trello Gold, just one of the default background colors.
