### ISSUE TITLE
CMD + H, CMD + M Don't Work (Trello)

### ISSUE THREAD

**Issue by joshdickson** [kfix/MacPin#7]
Hey, great project.

Should shortcuts be working?

Also, header shows up as black which looks sort of weird.

Not a Mac dev myself or I'd put in a PR, but thought I'd at least bring to your attn.

**Comment by kfix** [comment]
I could implement ⌘+M to minimize. 
⌘+H is a bit less straightforward...there are no static Home pages or bookmarks in MacPin apps, only an initial tab and "Shortcuts". Perhaps first shortcut made should always be ⌘+H?

The header is like FaceTime for Hacker/Dark Mode reasons and auto-hides in full screen (disabling minimize). Could make it a toggle.

**Comment by joshdickson** [comment]
⌘+H I'm implying to be 'hide', not home (Which I think is what you're referring to? Not sure). I did notice there is no 'hide' implemented so it's not just the shortcut that doesn't work.

Both are fairly standard for Mac apps, everything I use has them. Makes it hard to remember which one application doesn't have it implemented ;P 

I do have dark mode enabled on Mac OS X, but Safari is always light so it looks sort of off. Would be great to have a toggle.

Thanks.
